version: "3.9"
services:
  app:
    container_name: app
    environment:
      - PORT=${PORT}
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SYNCHRONIZE=${DATABASE_SYNCHRONIZE}
      - DATABASE_LOGGING=${DATABASE_LOGGING}
    build:
      args:
        - PORT=${PORT}
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mysql
  mysql:
    container_name: mysqldb
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - ./tmp/mysql:/var/lib/mysql
